### ISSUE TITLE
Feedback David Weiser /  No such file or directory: "r.cli.html"

### ISSUE THREAD

**Issue by DavidWei10** [wagner-science/Random-Forest-FOSSGIS#2]
Anbei mein Feedback zu eurem Projekt.

Die Dokumentation hier auf Github ist euch meiner Meinung nach sehr gelungen.

Eine genauere Erklärung beim Data preprocessing/Supervised Classification, insbesondere beim Anpassen des "wd_path" wäre allerdings hilfreich.

Für Personen wie mich, die mit Jupyter Notebooks noch gar nicht gearbeitet haben, und die Benutzeroberfläche nun zum ersten Mal sehen, wirkt das teilweise sehr verwirrend. Ich hab gesehen, dass ihr in der randomForestGRASS Datei ebenfalls Anmerkungen verwendet habt, hilfreicher meiner Meinung nach wäre z.B. aber  ein Screenshot mit Pfeilen, der die einzelnen Elemente, die umzubennen sind, deutlich zeigt.

Beim ersten Schritt, der Data acquisition, dem Ausführen der zwei Batch Skripte, kam bei mir ständig der Hinweis "curl: Failed writing body (0 != 7489)". Der Prozess ging trotzdem erfolgreich von statten, wollte euch das nur mitteilen bzw. könnt ihr euch ja vielleicht erklären, was die Fehlermeldung mitteilen möchte?

Bei dem [Kernel /Restart & Run All] Schritt tritt bei mir leider folgender Fehler auf:

![grafik](https://user-images.githubusercontent.com/73949391/108638659-95aa2300-7490-11eb-9341-4d3a14afa64a.png)

Ist dieser Fehler überhaupt zu berücksichtigen? Leider habe ich nach dem Ausführen des Befehls auch keine (neue) Model 3 Datei....

Ich habe alle aktuellen Programmversionen auf meinem PC. Ich habe die Anzahl der zwei Parameter "npoints"  und "n_estimator"  schon sehr niedrig gestellt, wie von euch empfohlen. 

Soll nach dem Kernel --> Restart & Run All dann das Programm neugestartet werden?`Weil ein "Restart" Menü finde ich nicht auf der Oberfläche von Jupyter Notebooks... Ein "Run all Cells" gibt es auch nicht, damit meint ihr aber bestimmt den Menüpunkt "Cell" --> "Run all"? Als Ergebnis bekommt dann nach diesem Schritt die Model 3 Datei?

**Comment by d-w216** [comment]
Vielen Dank für das Feedback. 

Der Hinweiß mit der Curl Abfrage ist auch hilfreich, da diese nur funktioniert wenn die OHSOME Betreiber keine Wartungsarbeiten durchführen. Diese Information haben wir ergänzt. 


Deine beschriebenen Probleme sind wahrscheinlich auf deine Programmversionen zurückzuführen. Zu Beginn der Beschreibung sind die benötigten programmversionen angegeben, diese exakten Versionen müssen auch installiert sein. 

Die Modell3 Datei ist ein Modellbuiloder für QGIS und gehört zu dem Saga Workflow.

Das Ergebniss des Jupyter Skriptes sind Layer in Grass Gis mit der fertigen Klassifikation. 

Wir hoffen diese Kommentare Helfen weiter. 

Viel Erfolg!
